import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { 
  AccessControlComponent,
  EditAccessControlComponent,
  AppComponent,
  AttachmentComponent,
  BookingComponent,
  EditBookingComponent,
  EditCompanyComponent,
  CompanyComponent,
  ContractComponent,
  EditContractComponent,
  ContractorComponent,
  EditContractorComponent,
  ContractNoticeComponent,
  ContractNoteComponent,
  DevelopmentComponent,
  EditDevelopmentComponent,
  DashboardComponent,
  FacilityComponent,
  EditFacilityComponent,
  HeaderComponent,
  IncidentComponent,
  EditIncidentComponent,
  LoginComponent,
  AuthGuard,
  RegisterComponent,
  NavbarComponent,
  NewsletterComponent,
  EditNewsletterComponent,
  PaymentComponent,
  PollComponent,
  QuotationComponent,
  SettingComponent,
  EditSettingComponent,
  UserComponent,
  EditUserComponent,
  UnitComponent,
  EditUnitComponent,
  ViewUnitComponent,
  UserGroupComponent,
  EditUserGroupComponent,
  VisitComponent,
  AnnouncementComponent,
  EditAnnouncementComponent,
  PetitionComponent,
  EditPetitionComponent,
  TestComponent
} from '../components/index';
const routes: Routes = [
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: 'login',  component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'user',     component: UserComponent, canActivate: [AuthGuard] },
  { path: 'user/add/:_id',   component: EditUserComponent },
  { path: 'user/edit/:name/:id',   component: EditUserComponent },
  { path: 'dashboard',     component: DashboardComponent },
  { path: 'newsletter',   component: NewsletterComponent },
  { path: 'newsletter/add',   component: EditNewsletterComponent },
  { path: 'newsletter/edit/:id',   component: EditNewsletterComponent },
  { path: 'incident',   component: IncidentComponent },
  { path: 'incident/add',   component: EditIncidentComponent },
  { path: 'incident/view/:id',   component: IncidentComponent },
  { path: 'contract',   component: ContractComponent },
  { path: 'contract/add',   component: EditContractComponent },
  { path: 'contract/add/:id',   component: EditContractComponent },
  { path: 'contract/add/note/:id',   component: ContractNoteComponent },
  { path: 'contract/add/notice/:id',   component: ContractNoticeComponent },
  { path: 'contract/view/:id',   component: ContractComponent },
  { path: 'contract/edit/:id',   component: EditContractComponent },
  { path: 'facility',   component: FacilityComponent },
  { path: 'facility/add',   component: EditFacilityComponent },
  { path: 'facility/view/:id',   component: FacilityComponent },
  { path: 'facility/edit/:id',   component: EditFacilityComponent },
  { path: 'booking',   component: BookingComponent },
  { path: 'booking/add',   component: EditBookingComponent },
  { path: 'booking/view/:id',   component: BookingComponent },
  { path: 'setting',     component: SettingComponent },
  { path: 'setting/edit/:id',     component: EditSettingComponent },
  { path: 'access_control',   component: AccessControlComponent },
  { path: 'access_control/add',   component: EditAccessControlComponent },
  { path: 'access_control/edit/:id',   component: EditAccessControlComponent },
  
  // { path: 'newsletter/edit/:name',   component: EditNewsletterComponent },
  { path: 'development',   component: DevelopmentComponent },
  { path: 'development/add',   component: EditDevelopmentComponent },
  { path: 'development/edit/:id',   component: EditDevelopmentComponent },

  { path: 'unit',   component: UnitComponent },
  { path: 'unit/add',   component: EditUnitComponent },
  // { path: 'unit/edit/:id',   component: EditUnitComponent },
  { path: 'unit/view/:id',   component: ViewUnitComponent },
  // { path: 'development/edit/:name',   component: EditDevelopmentComponent },
  { path: 'user_group',   component: UserGroupComponent },
  { path: 'user_group/add',   component: EditUserGroupComponent },
  { path: 'user_group/edit/:id',   component: EditUserGroupComponent },

  { path: 'announcement',   component: AnnouncementComponent },
  { path: 'announcement/add',   component: EditAnnouncementComponent },
  { path: 'announcement/edit/:id',   component: EditAnnouncementComponent },

  { path: 'petition', component: PetitionComponent },
  { path: 'petition/view/:id', component: PetitionComponent },
  { path: 'petition/add',   component: EditPetitionComponent },

   { path: 'visit', component: VisitComponent },


  { path: 'company', component: CompanyComponent },
  { path: 'company/edit/:id',   component: EditCompanyComponent },
  { path: 'company/add',   component: EditCompanyComponent },

  { path: 'contractor', component: ContractorComponent },
  { path: 'contractor/edit/:id', component: EditContractorComponent },
  { path: 'contractor/add',   component: EditContractorComponent },

  // { path: 'petition/edit/:id',   component: EditAnnouncementComponent },
  // { path: 'form',     component: HeroFormComponent },
  // { path: 'table',     component: TableDemoComponent },
  { path: 'test',     component: TestComponent },
  
];

@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
