import { NgModule, Directive, ElementRef  }          from '@angular/core';
import { CommonModule }                 from '@angular/common';
import { BrowserModule }                from '@angular/platform-browser';
import { FormsModule }  				        from '@angular/forms';
import { FileSelectDirective }          from 'ng2-file-upload';
import { SimpleNotificationsModule }    from 'angular2-notifications';
import { FileDropDirective }            from 'ng2-file-upload';
import { ReactiveFormsModule }			    from '@angular/forms';
import { HttpModule }                   from '@angular/http';
import { Ng2BootstrapModule, PaginationModule, DatepickerModule, TabsModule, PopoverModule, ProgressbarModule  } from 'ng2-bootstrap';
import { SelectModule }                 from 'ng2-select/ng2-select';
import { MyDatePickerModule }           from 'mydatepicker';
import { SignaturePadModule }           from 'angular2-signaturepad';
import { signature_pad }                from 'signature_pad';
import { SignaturePad } from 'angular2-signaturepad/signature-pad';
// import { DatePickerModule }             from 'ng2-datepicker';
// import { SELECT_DIRECTIVES }            from 'ng2-select';
import { AppRoutingModule }     		    from './app-routing.module';
import { url }                          from '../global'
import { DataTableModule,SharedModule,ScheduleModule,DialogModule,InputMaskModule,CheckboxModule,PanelModule,FieldsetModule,CalendarModule } from 'primeng/primeng';
import { EqualValidator }               from '../components/user/equal-validator.directive';
import { ImageUploadModule }            from 'ng2-imageupload';
import { ModalModule }                  from "ngx-modal";
import { BootstrapModalModule }         from 'angular2-modal/plugins/bootstrap';
import { SlimLoadingBarModule } from 'ng2-slim-progress-bar';
import { MomentModule }                 from 'angular2-moment';

import { 
  AccessControlComponent,
  EditAccessControlComponent,
  AlertComponent,
  AppComponent,
  AttachmentComponent,
  AnnouncementComponent,
  EditAnnouncementComponent,
  // PublishAnnouncementModalComponent,
  BookingComponent,
  EditBookingComponent,
  CompanyComponent,
  EditCompanyComponent,
  ContractComponent,
  EditContractComponent,
  ContractNoticeComponent,
  ContractNoteComponent,
  ContractorComponent,
  EditContractorComponent,
  DashboardComponent,
  DevelopmentComponent,
  EditDevelopmentComponent, 
  FacilityComponent,
  EditFacilityComponent,
  FeedbackComponent,
  HeaderComponent,
  IncidentComponent,
  EditIncidentComponent,
  LoginComponent,
  AuthGuard,
  NavbarComponent,
  NewsletterComponent,
  EditNewsletterComponent,
  PaymentComponent,
  EditPaymentComponent,
  PaymentReminderComponent,
  EditPaymentReminderComponent,
  PetitionComponent,
  EditPetitionComponent,
  PollComponent,
  EditPollComponent,
  QuotationComponent,
  RegisterComponent,
  SettingComponent,
  EditSettingComponent,
  UserComponent,
  EditUserComponent,
  UnitComponent,
  EditUnitComponent,
  ViewUnitComponent,
  UserGroupComponent,
  EditUserGroupComponent,
  VisitComponent,
  TestComponent,
  Galleria,
  NotificationComponent,
  LostFoundComponent,
  EditLostFoundComponent,

  SignaturePadPage,
} from '../components/index';

import {
  AccessControlService,
  AlertService,
  AnnouncementService,
  AuthenticationService,
  BookingService,
  CompanyService,
  ContractService,
  ContractNoteService,
  ContractNoticeService,
  ContractorService,
  DevelopmentService,
  FacilityService,
  FeedbackService,
  IncidentService,
  NewsletterService,
  PaymentService,
  PaymentReminderService,
  NotificationService,
  PetitionService,
  PollService,
  QuotationService,
  UserService,
  UserGroupService,
  UnitService,
  VisitService,
  LostFoundService,
  TestService,
} from '../services/index';

@NgModule({
  imports:      [
    CommonModule, 
    DataTableModule,  
  	BrowserModule,
  	FormsModule,
  	ReactiveFormsModule,
  	HttpModule,
  	Ng2BootstrapModule,
  	PaginationModule,
  	AppRoutingModule,
    SharedModule,
    SignaturePadModule,
    ScheduleModule,
    DialogModule,
    InputMaskModule,
    CheckboxModule,
    SelectModule,
    PanelModule,
    FieldsetModule,
    DatepickerModule.forRoot(),
    SimpleNotificationsModule,
    // ModalModule.forRoot(),
    TabsModule.forRoot(),
    ModalModule,
    BootstrapModalModule,
    MyDatePickerModule,
    PopoverModule.forRoot(),
    CalendarModule,
    ImageUploadModule,
    MomentModule,
    SlimLoadingBarModule.forRoot(),
    ProgressbarModule.forRoot()
  ],
  declarations: [ 
    AccessControlComponent,
    EditAccessControlComponent,
    EqualValidator,
    AlertComponent,
  	AppComponent,
    AttachmentComponent,
    BookingComponent,
    EditBookingComponent,
    CompanyComponent,
    EditCompanyComponent,
    ContractComponent,
    EditContractComponent,
    ContractNoticeComponent,
    ContractNoteComponent,
    ContractorComponent,
    EditContractorComponent,
    DashboardComponent,
    DevelopmentComponent,
    EditDevelopmentComponent,
    FacilityComponent,
    EditFacilityComponent,
    FeedbackComponent,
    FileSelectDirective,
    HeaderComponent,
    IncidentComponent,
    EditIncidentComponent,
    LoginComponent,
    NavbarComponent,
    NewsletterComponent,
    EditNewsletterComponent,
    PaymentComponent,
    EditPaymentComponent,
    PaymentReminderComponent,
    EditPaymentReminderComponent,
    PetitionComponent,
    EditPetitionComponent,
    PollComponent,
    EditPollComponent,
    QuotationComponent,
    RegisterComponent,
    SettingComponent,
    EditSettingComponent,
    UserComponent,
    EditUserComponent,
    EditUnitComponent,
    UnitComponent,
    ViewUnitComponent,
    UserGroupComponent,
    EditUserGroupComponent,
    VisitComponent, 
    AnnouncementComponent,
    EditAnnouncementComponent,
    TestComponent,
    Galleria,
    NotificationComponent,
    LostFoundComponent,
    EditLostFoundComponent,
    SignaturePadPage,
  ],
  providers: [ 
    AccessControlService,
    AlertService,
    AnnouncementService,
    AuthenticationService,
    AuthGuard,
    BookingService,
    CompanyService,
    ContractService,
    ContractNoteService,
    ContractNoticeService,
    ContractorService,
    DevelopmentService,
    FacilityService,
    FeedbackService,
    IncidentService,
    NewsletterService,
    NotificationService,
    PaymentService,
    PaymentReminderService,
    PetitionService,
    PollService,
    QuotationService,
    UserService,
    UnitService,
    UserGroupService,
    VisitService,
    LostFoundService,
    TestService,
    EditContractComponent,
  ],
  bootstrap:    [ AppComponent ],
  // entryComponents: [ PublishAnnouncementModalComponent ] 
})
export class AppModule { }
